apiVersion: apps/v1
kind: Service
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: phandamien/devops-app:latest
        ports:
        - containerPort: 5000
