groups:
- name: cpu-alerts
  rules:
  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total[1m])) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU Usage Detected"
